version: "3"
services:
  server:
    image: "powdermountain/tsc-express"
    container_name: tiger-shit-coffee-module
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_USERNAME: tsc
      MONGO_PASSWORD: tsc
      MONGO_DATABASE: tsc
      MONGO_AUTH_SOURCE: admin
      MONGO_PORT: 27017
    ports:
      - 8083:3000
    networks:
      - tiger-shit-coffee-module

  mongo:
    image: "mongo:6.0"
    networks:
      - tiger-shit-coffee-module
    container_name: tiger-shit-coffee-mongo
    volumes:
      - /opt/tiger-shit-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: tsc
      MONGO_INITDB_ROOT_PASSWORD: tsc
      MONGO_INITDB_DATABASE: tsc
networks:
  tiger-shit-coffee-module:
